// Mocks generated by Mockito 5.4.6 from annotations
// in forex_ai_frontend/test/config_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:forex_ai_frontend/brokers/broker_interface.dart' as _i7;
import 'package:forex_ai_frontend/models/enums.dart' as _i5;
import 'package:forex_ai_frontend/models/models.dart' as _i2;
import 'package:forex_ai_frontend/services/backend_service.dart' as _i6;
import 'package:forex_ai_frontend/services/storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBackendSignal_0 extends _i1.SmartFake implements _i2.BackendSignal {
  _FakeBackendSignal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerformanceMetrics_1 extends _i1.SmartFake
    implements _i2.PerformanceMetrics {
  _FakePerformanceMetrics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSentimentOverview_2 extends _i1.SmartFake
    implements _i2.SentimentOverview {
  _FakeSentimentOverview_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRiskParams_3 extends _i1.SmartFake implements _i2.RiskParams {
  _FakeRiskParams_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountInfo_4 extends _i1.SmartFake implements _i2.AccountInfo {
  _FakeAccountInfo_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveBackendConfig(
    String? url,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBackendConfig,
          [
            url,
            apiKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String?>> getBackendConfig() => (super.noSuchMethod(
        Invocation.method(
          #getBackendConfig,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i4.Future<Map<String, String?>>);

  @override
  _i4.Future<void> saveBrokerConfig(
    _i5.BrokerType? type,
    Map<String, String>? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBrokerConfig,
          [
            type,
            credentials,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getBrokerConfig() => (super.noSuchMethod(
        Invocation.method(
          #getBrokerConfig,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> saveTradingMode(_i5.TradingMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTradingMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i5.TradingMode getTradingMode() => (super.noSuchMethod(
        Invocation.method(
          #getTradingMode,
          [],
        ),
        returnValue: _i5.TradingMode.normal,
      ) as _i5.TradingMode);

  @override
  _i4.Future<void> saveActivePairs(List<_i5.CurrencyPair>? pairs) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivePairs,
          [pairs],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i5.CurrencyPair> getActivePairs() => (super.noSuchMethod(
        Invocation.method(
          #getActivePairs,
          [],
        ),
        returnValue: <_i5.CurrencyPair>[],
      ) as List<_i5.CurrencyPair>);

  @override
  _i4.Future<void> saveEngineState(bool? running) => (super.noSuchMethod(
        Invocation.method(
          #saveEngineState,
          [running],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getEngineState() => (super.noSuchMethod(
        Invocation.method(
          #getEngineState,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearApiKey() => (super.noSuchMethod(
        Invocation.method(
          #clearApiKey,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [BackendService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendService extends _i1.Mock implements _i6.BackendService {
  MockBackendService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> testConnection(
    String? url,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [
            url,
            apiKey,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getStatus() => (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.BackendSignal> getSignal(String? pair) => (super.noSuchMethod(
        Invocation.method(
          #getSignal,
          [pair],
        ),
        returnValue: _i4.Future<_i2.BackendSignal>.value(_FakeBackendSignal_0(
          this,
          Invocation.method(
            #getSignal,
            [pair],
          ),
        )),
      ) as _i4.Future<_i2.BackendSignal>);

  @override
  _i4.Future<List<_i2.BackendSignal>> getAllSignals(
          {String? timeframe = 'H1'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSignals,
          [],
          {#timeframe: timeframe},
        ),
        returnValue:
            _i4.Future<List<_i2.BackendSignal>>.value(<_i2.BackendSignal>[]),
      ) as _i4.Future<List<_i2.BackendSignal>>);

  @override
  _i4.Future<Map<String, dynamic>> getMarket(String? pair) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarket,
          [pair],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.OpenTrade>> getOpenTrades() => (super.noSuchMethod(
        Invocation.method(
          #getOpenTrades,
          [],
        ),
        returnValue: _i4.Future<List<_i2.OpenTrade>>.value(<_i2.OpenTrade>[]),
      ) as _i4.Future<List<_i2.OpenTrade>>);

  @override
  _i4.Future<List<_i2.TradeRecord>> getTradeHistory({
    DateTime? dateFrom,
    DateTime? dateTo,
    String? pair,
    String? strategy,
    int? page = 1,
    int? size = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTradeHistory,
          [],
          {
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #pair: pair,
            #strategy: strategy,
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.TradeRecord>>.value(<_i2.TradeRecord>[]),
      ) as _i4.Future<List<_i2.TradeRecord>>);

  @override
  _i4.Future<_i2.PerformanceMetrics> getPerformance() => (super.noSuchMethod(
        Invocation.method(
          #getPerformance,
          [],
        ),
        returnValue:
            _i4.Future<_i2.PerformanceMetrics>.value(_FakePerformanceMetrics_1(
          this,
          Invocation.method(
            #getPerformance,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PerformanceMetrics>);

  @override
  _i4.Future<List<_i2.NewsItem>> getNews(String? pair) => (super.noSuchMethod(
        Invocation.method(
          #getNews,
          [pair],
        ),
        returnValue: _i4.Future<List<_i2.NewsItem>>.value(<_i2.NewsItem>[]),
      ) as _i4.Future<List<_i2.NewsItem>>);

  @override
  _i4.Future<List<_i2.NewsItem>> getAllNews({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNews,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.NewsItem>>.value(<_i2.NewsItem>[]),
      ) as _i4.Future<List<_i2.NewsItem>>);

  @override
  _i4.Future<_i2.SentimentOverview> getSentimentOverview() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentimentOverview,
          [],
        ),
        returnValue:
            _i4.Future<_i2.SentimentOverview>.value(_FakeSentimentOverview_2(
          this,
          Invocation.method(
            #getSentimentOverview,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SentimentOverview>);

  @override
  _i4.Future<Map<String, dynamic>> getAllCOT() => (super.noSuchMethod(
        Invocation.method(
          #getAllCOT,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSentimentHistory(
          String? currency) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentimentHistory,
          [currency],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i2.OHLCVBar>> getOHLCV(
    String? pair, {
    String? timeframe = 'H1',
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOHLCV,
          [pair],
          {
            #timeframe: timeframe,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.OHLCVBar>>.value(<_i2.OHLCVBar>[]),
      ) as _i4.Future<List<_i2.OHLCVBar>>);

  @override
  _i4.Future<List<_i2.IndicatorSet>> getIndicators(
    String? pair, {
    String? timeframe = 'H1',
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIndicators,
          [pair],
          {
            #timeframe: timeframe,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.IndicatorSet>>.value(<_i2.IndicatorSet>[]),
      ) as _i4.Future<List<_i2.IndicatorSet>>);

  @override
  _i4.Future<List<_i2.SMCZone>> getSMCZones(
    String? pair, {
    String? timeframe = 'H1',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSMCZones,
          [pair],
          {#timeframe: timeframe},
        ),
        returnValue: _i4.Future<List<_i2.SMCZone>>.value(<_i2.SMCZone>[]),
      ) as _i4.Future<List<_i2.SMCZone>>);

  @override
  _i4.Future<List<_i2.CalendarEvent>> getCalendar() => (super.noSuchMethod(
        Invocation.method(
          #getCalendar,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CalendarEvent>>.value(<_i2.CalendarEvent>[]),
      ) as _i4.Future<List<_i2.CalendarEvent>>);

  @override
  _i4.Future<_i2.RiskParams> getRisk() => (super.noSuchMethod(
        Invocation.method(
          #getRisk,
          [],
        ),
        returnValue: _i4.Future<_i2.RiskParams>.value(_FakeRiskParams_3(
          this,
          Invocation.method(
            #getRisk,
            [],
          ),
        )),
      ) as _i4.Future<_i2.RiskParams>);

  @override
  _i4.Future<void> postSettings(
    _i5.TradingMode? mode,
    List<_i5.CurrencyPair>? pairs,
    Map<String, double>? risk,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postSettings,
          [
            mode,
            pairs,
            risk,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> postRetrain() => (super.noSuchMethod(
        Invocation.method(
          #postRetrain,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [BrokerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrokerInterface extends _i1.Mock implements _i7.BrokerInterface {
  MockBrokerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  String get brokerName => (super.noSuchMethod(
        Invocation.getter(#brokerName),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#brokerName),
        ),
      ) as String);

  @override
  _i4.Future<bool> connect(Map<String, String>? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [credentials],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AccountInfo> getAccountInfo() => (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.AccountInfo>.value(_FakeAccountInfo_4(
          this,
          Invocation.method(
            #getAccountInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AccountInfo>);

  @override
  _i4.Future<List<_i2.OpenTrade>> getOpenTrades() => (super.noSuchMethod(
        Invocation.method(
          #getOpenTrades,
          [],
        ),
        returnValue: _i4.Future<List<_i2.OpenTrade>>.value(<_i2.OpenTrade>[]),
      ) as _i4.Future<List<_i2.OpenTrade>>);

  @override
  _i4.Future<List<_i2.CalendarEvent>> getCalendar() => (super.noSuchMethod(
        Invocation.method(
          #getCalendar,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CalendarEvent>>.value(<_i2.CalendarEvent>[]),
      ) as _i4.Future<List<_i2.CalendarEvent>>);

  @override
  _i4.Future<double> getLiveSpread(_i5.CurrencyPair? pair) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLiveSpread,
          [pair],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<String> placeOrder(
    _i5.CurrencyPair? pair,
    _i5.Direction? direction,
    double? lotSize,
    double? stopLoss,
    double? takeProfit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeOrder,
          [
            pair,
            direction,
            lotSize,
            stopLoss,
            takeProfit,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #placeOrder,
            [
              pair,
              direction,
              lotSize,
              stopLoss,
              takeProfit,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<bool> closeOrder(String? ticketId) => (super.noSuchMethod(
        Invocation.method(
          #closeOrder,
          [ticketId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> closeAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #closeAllOrders,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> closeOrdersInProfit() => (super.noSuchMethod(
        Invocation.method(
          #closeOrdersInProfit,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> closeOrdersAtLoss() => (super.noSuchMethod(
        Invocation.method(
          #closeOrdersAtLoss,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<_i2.OpenTrade> tradeUpdates() => (super.noSuchMethod(
        Invocation.method(
          #tradeUpdates,
          [],
        ),
        returnValue: _i4.Stream<_i2.OpenTrade>.empty(),
      ) as _i4.Stream<_i2.OpenTrade>);
}
