// Mocks generated by Mockito 5.4.6 from annotations
// in forex_ai_frontend/test/dashboard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:forex_ai_frontend/models/enums.dart' as _i4;
import 'package:forex_ai_frontend/services/storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveBackendConfig(
    String? url,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBackendConfig,
          [
            url,
            apiKey,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String?>> getBackendConfig() => (super.noSuchMethod(
        Invocation.method(
          #getBackendConfig,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<void> saveBrokerConfig(
    _i4.BrokerType? type,
    Map<String, String>? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBrokerConfig,
          [
            type,
            credentials,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getBrokerConfig() => (super.noSuchMethod(
        Invocation.method(
          #getBrokerConfig,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> saveTradingMode(_i4.TradingMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTradingMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.TradingMode getTradingMode() => (super.noSuchMethod(
        Invocation.method(
          #getTradingMode,
          [],
        ),
        returnValue: _i4.TradingMode.normal,
      ) as _i4.TradingMode);

  @override
  _i3.Future<void> saveActivePairs(List<_i4.CurrencyPair>? pairs) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActivePairs,
          [pairs],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.CurrencyPair> getActivePairs() => (super.noSuchMethod(
        Invocation.method(
          #getActivePairs,
          [],
        ),
        returnValue: <_i4.CurrencyPair>[],
      ) as List<_i4.CurrencyPair>);

  @override
  _i3.Future<void> saveEngineState(bool? running) => (super.noSuchMethod(
        Invocation.method(
          #saveEngineState,
          [running],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getEngineState() => (super.noSuchMethod(
        Invocation.method(
          #getEngineState,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearApiKey() => (super.noSuchMethod(
        Invocation.method(
          #clearApiKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
